# Generated by Django 4.2.5 on 2023-10-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_app', '0002_sensordata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
