# Generated by Django 4.2.5 on 2023-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_app', '0003_alter_sensordata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
