# Generated by Django 4.2.5 on 2023-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='moisture',
            field=models.FloatField(null=True),
        ),
    ]
