# Generated by Django 4.2.5 on 2023-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
