# Generated by Django 4.2.5 on 2023-09-23 11:31

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_alter_product_id'),
    ]
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('num_of_products', models.IntegerField()),
            ],
        ),
    ]    
